# Generated by Django 4.2.2 on 2023-07-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('pwd', models.CharField(max_length=30)),
                ('contactno', models.CharField(max_length=15)),
                ('adhar', models.CharField(default='000000000000', max_length=12)),
                ('photo', models.ImageField(upload_to='client_data')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
