# Generated by Django 4.2.2 on 2023-07-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('contry', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=8)),
                ('education', models.CharField(max_length=30)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
